spring:
  application:
    name: lms

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.sam.lms: DEBUG
    org.hibernate.orm.jdbc.bind: trace

secret:
  x-api-key: aXC8zK6puHIf9l53L8TiQg==
  aes-secret: secret-key-12345
  jwt:
    security-key: tkaWjatkaRhrqnxrhtlvtmqslekwkqkwjdakfwkfgkfwktlsdlTtmqslekrkatkgkqslek