server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: lms-service
          uri: lb://lms-service
          predicates:
            - Path=/api/lms/**
        - id: store-service
          uri: lm://store-service
          predicates:
            - Path=/api/store/**
    discovery:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
