server:
  port: 8081
  servlet:
    encoding:
          charset: UTF-8
          enabled: true
          force: true

spring:
  application:
    name: lms

  config:
    import:
      - application-domain.yml
      - application-infrastructure.yml

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none



logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.sam.lms: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.orm.jpa: TRACE

secret:
  x-api-key: aXC8zK6puHIf9l53L8TiQg==
  aes-secret: secret-key-12345
  jwt:
    security-key: tkaWjatkaRhrqnxrhtlvtmqslekwkqkwjdakfwkfgkfwktlsdlTtmqslekrkatkgkqslek

