server:
  port: 8082
  servlet:
    encoding:
          charset: UTF-8
          enabled: true
          force: true

spring:
  application:
    name: store

  config:
    import:
      - application-domain.yml

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none



logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.sam.lms: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.orm.jpa: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
