spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: 1111
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000